#define NCURSESPLUS_VERSION_MAJOR @NCursesPlus_VERSION_MAJOR@
#define NCURSESPLUS_VERSION_MINOR @NCursesPlus_VERSION_MINOR@
#define NCURSESPLUS_VERSION_PATCH @NCursesPlus_VERSION_PATCH@
#define NCURSESPLUS_RELEASE_TYPE "@NCursesPlus_RELEASE_TYPE@"
